package com.capitals

object Data {

    var questionCount: Int = 1
    var countAswerGood: Int = 0
    var countAnswerNot: Int = 0

    val countryCityRu = mutableMapOf(
        "Австралия" to "Канберра",
        "Австрия" to "Вена",
        "Азербайджан" to "Баку",
        "Албания" to "Тирана",
        "Алжир" to "Алжир",
        "Ангола" to "Луанда",
        "Андорра" to "Андорра - ла - Велья",
        "Антигуа и Барбуда" to "Сент - Джонс",
        "Аргентина" to "Буэнос - Айрес",
        "Армения" to "Ереван",
        "Аруба" to "Ораньестад",
        "Афганистан" to "Кабул",
        "Багамы" to "Нассау",
        "Бангладеш" to "Дакка",
        "Барбадос" to "Бриджтаун",
        "Бахрейн" to "Манама",
        "Беларусь" to "Минск",
        "Белиз" to "Бельмопан",
        "Бельгия" to "Брюссель",
        "Бенин" to "Порто-Ново, Котону",
        "Бермудские острова" to "Гамильтон",
        "Болгария" to "София",
        "Боливия" to "Сукре",
        "Босния и Герцеговина" to "Сараево",
        "Ботсвана" to "Габороне",
        "Бразилия" to "Бразилиа",
        "Бруней" to "Бандар-Сери-Бегаван",
        "Буркина Фасо" to "Уагадугу",
        "Бурунди" to "Бужумбура",
        "Бутан" to "Тхимпху",
        "Вануату" to "Порт-Вила",
        "Ватикан" to "Ватикан",
        "Великобритания" to "Лондон",
        "Венгрия" to "Будапешт",
        "Венесуэла" to "Каракас",
        "Вьетнам" to "Ханой",
        "Габон" to "Либревиль",
        "Гавайские острова" to "Гонолулу",
        "Гайана" to "Джорджтаун",
        "Гаити" to "Порт-о-Пренс",
        "Гамбия" to "Банжул",
        "Гана" to "Аккра",
        "Гваделупа" to "Бас-Тер",
        "Гватемала" to "Гватемала",
        "Гвинея" to "Конакри",
        "Гвинея-Бисау" to "Бисау",
        "Германия" to "Берлин",
        "Гондурас" to "Тегусигальпа",
        "Гонконг" to "Гонконг",
        "Гренада" to "Сент-Джорджес",
        "Греция" to "Афины",
        "Грузия" to "Тбилиси",
        "Дания" to "Копенгаген",
        "Джибути" to "Джибути",
        "Доминика" to "Розо",
        "Доминикана" to "Санто-Доминго",
        "Египет" to "Каир",
        "Замбия" to "Лусака",
        "Зимбабве" to "Хараре",
        "Израиль" to "Иерусалим",
        "Индия" to "Нью-Дели",
        "Индонезия" to "Джакарта",
        "Иордания" to "Амман",
        "Ирак" to "Багдад",
        "Иран" to "Тегеран",
        "Ирландия" to "Дублин",
        "Исландия" to "Рейкьявик",
        "Испания" to "Мадрид",
        "Италия" to "Рим",
        "Йемен" to "Сана",
        "Кабо-Верде" to "Прая",
        "Казахстан" to "Астана",
        "Каймановы острова" to "Джорджтаун",
        "Камбоджа" to "Пномпень",
        "Камерун" to "Яунде",
        "Канада" to "Оттава",
        "Канарские острова" to "Испания",
        "Катар" to "Доха",
        "Кения" to "Найроби",
        "Кипр" to "Никосия",
        "Киргизия" to "Бишкек",
        "Кирибати" to "Южная Тарава",
        "Китай" to "Пекин",
        "Колумбия" to "Санта-Фе-Де-Богота",
        "Коморы" to "Морони",
        "Конго" to "Браззавиль",
        "Конго-Киншаса" to "Киншаса",
        "Коста-Рика" to "Сан-Хосе",
        "Кот-д’Ивуар" to "Ямусукро",
        "Куба" to "Гавана",
        "Кувейт" to "Эль-Кувейт",
        "Лаос" to "Вьентьян",
        "Латвия" to "Рига",
        "Лесото" to "Масеру",
        "Либерия" to "Монровия",
        "Ливан" to "Бейрут",
        "Ливия" to "Триполи",
        "Литва" to "Вильнюс",
        "Лихтенштейн" to "Вадуц",
        "Люксембург" to "Люксембург",
        "Маврикий" to "Порт-Луи",
        "Мавритания" to "Нуакшот",
        "Мадагаскар" to "Антананариву",
        "Македония" to "Скопье",
        "Малави" to "Лилонгве",
        "Малайзия" to "Куала-Лумпур",
        "Мали" to "Бамако",
        "Мальдивы" to "Мале",
        "Мальта" to "Валлетта",
        "Марокко" to "Рабат",
        "Мартиника" to "Фор-де-Франс",
        "Маршалловы острова" to "Маджуро",
        "Мексика" to "Мехико",
        "Мозамбик" to "Мапуту",
        "Молдова" to "Кишинев",
        "Монако" to "Монако",
        "Монголия" to "Улан-Батор",
        "Мьянма" to "Нейпьидо",
        "Намибия" to "Виндхук",
        "Науру" to "Ярен",
        "Непал" to "Катманду",
        "Нигер" to "Ниамей",
        "Нигерия" to "Абуджа",
        "Нидерланды" to "Амстердам",
        "Никарагуа" to "Манагуа",
        "Новая Зеландия" to "Веллингтон",
        "Норвегия" to "Осло",
        "ОАЭ" to "Абу-Даби",
        "Оман" to "Маскат",
        "Остров Святой Елены" to "Джеймстаун",
        "Пакистан" to "Исламабад",
        "Палау" to "Нгерулмуд",
        "Панама" to "Панама",
        "Папуа - Новая Гвинея" to "Порт-Морсби",
        "Парагвай" to "Асунсьон",
        "Перу" to "Лима",
        "Польша" to "Варшава",
        "Португалия" to "Лиссабон",
        "Пуэрто-Рико" to "Сан-Хуан",
        "Реюньон" to "Сен-Дени",
        "Россия" to "Москва",
        "Руанда" to "Кигали",
        "Румыния" to "Бухарест",
        "Сальвадор" to "Сан-Сальвадор",
        "Самоа" to "Апиа",
        "Сан-Марино" to "Сан-Марино",
        "Сан-Томе и Принсипи" to "Сан-Томе",
        "Саудовская Аравия" to "Эр-Рияд",
        "Свазиленд" to "Мбабане, Лобамба",
        "Северная Корея" to "Пхеньян",
        "Сейшелы" to "Виктория",
        "Сенегал" to "Дакар",
        "Сен-Мартен" to "Мариго",
        "Сент-Винсент и Гренадины" to "Кингстаун",
        "Сент-Китс и Невис" to "Бастер",
        "Сент-Люсия" to "Кастри",
        "Сербия" to "Белград",
        "Сингапур" to "Сингапур",
        "Сирия" to "Дамаск",
        "Словакия" to "Братислава",
        "Словения" to "Любляна",
        "Соломоновы Острова" to "Хониара",
        "Сомали" to "Могадишо",
        "Судан" to "Хартум",
        "Суринам" to "Парамарибо",
        "США" to "Вашингтон",
        "Сьерра-Леоне" to "Фритаун",
        "Таджикистан" to "Душанбе",
        "Тайвань" to "Тайбэй",
        "Тайланд" to "Бангкок",
        "Танзания" to "Додома, Дар-эс-Салам",
        "Того" to "Ломе",
        "Тонга" to "Нукуалофа",
        "Тринидад и Тобаго" to "Порт-оф-Спейн",
        "Тувалу" to "Фунафути",
        "Тунис" to "Тунис",
        "Туркменистан" to "Ашхабад",
        "Турция" to "Анкара",
        "Уганда" to "Кампала",
        "Узбекистан" to "Ташкент",
        "Украина" to "Киев",
        "Уоллис и Футуна" to "Мата-Уту",
        "Уругвай" to "Монтевидео",
        "Фиджи" to "Сува",
        "Филиппины" to "Манила",
        "Финляндия" to "Хельсинки",
        "Франция" to "Париж",
        "Хорватия" to "Загреб",
        "Центрально-африканская республика" to "Банги",
        "Чад" to "Нджамена",
        "Черногория" to "Подгорица",
        "Чехия" to "Прага",
        "Чили" to "Сантьяго",
        "Швейцария" to "Берн",
        "Швеция" to "Стокгольм",
        "Шри-Ланка" to "Шри-Джаяварденепура-Котте",
        "Эквадор" to "Кито",
        "Экваториальная Гвинея" to "Малабо",
        "Эритрея" to "Асмэра",
        "Эстония" to "Таллин",
        "Эфиопия" to "Аддис-Абеба",
        "ЮАР" to "Кейптаун Претория",
        "Южная Корея" to "Сеул",
        "Ямайка" to "Кингстон",
        "Япония" to "Токио"
    )

    val countryCityEn = mutableMapOf(
        "Australia" to "Canberra", "Austria" to "Vienna",
        "Azerbaijan" to "Baku",
        "Albania" to "Tirana",
        "Algeria" to "Algeria",
        "Angola" to "Luanda",
        "Andorra" to "Andorra la Velha",
        "Antigua and Barbuda" to "St. Johns",
        "Argentina" to "Buenos Aires",
        "Armenia" to "Yerevan",
        "Aruba" to "Oranjestad",
        "Afghanistan" to "Kabul",
        "Bahamas" to "Nassau",
        "Bangladesh" to "Dhaka",
        "Barbados" to "Bridgetown",
        "Bahrain" to "Manama",
        "Belarus" to "Minsk",
        "Belize" to "Belmopan",
        "Belgium" to "Brussels",
        "Benin" to "Porto Novo, Cotonou",
        "Bermuda" to "Hamilton",
        "Bulgaria" to "Sofia",
        "Bolivia" to "Sucre",
        "Bosnia and Herzegovina" to "Sarajevo",
        "Botswana" to "Gaborone",
        "Brazil" to "Brasilia",
        "Brunei" to "Bandar Seri Begawan",
        "Burkina Faso" to "Ouagadougou",
        "Burundi" to "Bujumbura",
        "Bhutan" to "Thimphu",
        "Vanuatu" to "Port Vila",
        "Vatican" to "Vatican",
        "Great Britain" to "London",
        "Hungary" to "Budapest",
        "Venezuela" to "Caracas",
        "Vietnam" to "Hanoi",
        "Gabon" to "Libreville",
        "Hawaiian Islands" to "Honolulu",
        "Guyana" to "Georgetown",
        "Haiti" to "Port-au-Prince",
        "Gambia" to "Banjul",
        "Ghana" to "Accra",
        "Guadeloupe" to "Bas-Ter",
        "Guatemala" to "Guatemala",
        "Guinea" to "Conakry",
        "Guinea-Bissau" to "Bissau",
        "Germany" to "Berlin",
        "Honduras" to "Tegucigalpa",
        "Hong Kong" to "Hong Kong",
        "Grenada" to "St. Georges",
        "Greece" to "Athens",
        "Georgia" to "Tbilisi",
        "Denmark" to "Copenhagen",
        "Djibouti" to "Djibouti",
        "Dominica" to "Roseau",
        "Dominican Republic" to "Santo Domingo",
        "Egypt" to "Cairo",
        "Zambia" to "Lusaka",
        "Zimbabwe" to "Harare",
        "Israel" to "Jerusalem",
        "India" to "New Delhi",
        "Indonesia" to "Jakarta",
        "Jordan" to "Amman",
        "Iraq" to "Baghdad",
        "Iran" to "Tehran",
        "Ireland" to "Dublin",
        "Iceland" to "Reykjavik",
        "Spain" to "Madrid",
        "Italy" to "Rome",
        "Yemen" to "Sana'a",
        "Cape Verde" to "Praia",
        "Kazakhstan" to "Astana",
        "Cayman Islands" to "Georgetown",
        "Cambodia" to "Phnom Penh",
        "Cameroon" to "Yaounde",
        "Canada" to "Ottawa",
        "Canary Islands" to "Spain",
        "Qatar" to "Doha",
        "Kenya" to "Nairobi",
        "Cyprus" to "Nicosia",
        "Kyrgyzstan" to "Bishkek",
        "Kiribati" to "South Tarava",
        "China" to "Beijing",
        "Colombia" to "Santa Fe De Bogota",
        "Comoros" to "Moroni",
        "Congo" to "Brazzaville",
        "Congo-Kinshasa" to "Kinshasa",
        "Costa Rica" to "San Jose",
        "Côte d’Ivoire" to "Yamoussoukro",
        "Cuba" to "Havana",
        "Kuwait" to "Kuwait",
        "Laos" to "Vientiane",
        "Latvia" to "Riga",
        "Lesotho" to "Maseru",
        "Liberia" to "Monrovia",
        "Lebanon" to "Beirut",
        "Libya" to "Tripoli",
        "Lithuania" to "Vilnius",
        "Liechtenstein" to "Vaduz",
        "Luxembourg" to "Luxembourg",
        "Mauritius" to "Port Louis",
        "Mauritania" to "Nouakchott",
        "Madagascar" to "Antananarivo",
        "Macedonia" to "Skopje",
        "Malawi" to "Lilongwe",
        "Malaysia" to "Kuala Lumpur",
        "Mali" to "Bamako",
        "Maldives" to "Male",
        "Malta" to "Valletta",
        "Morocco" to "Rabat",
        "Martinique" to "Fort de France",
        "Marshall Islands" to "Majuro",
        "Mexico" to "Mexico City",
        "Mozambique" to "Maputo",
        "Moldova" to "Chisinau",
        "Monaco" to "Monaco",
        "Mongolia" to "Ulan Bator",
        "Myanmar" to "Naypyidaw",
        "Namibia" to "Windhoek",
        "Nauru" to "Yaren",
        "Nepal" to "Kathmandu",
        "Niger" to "Niamey",
        "Nigeria" to "Abuja",
        "Netherlands" to "Amsterdam",
        "Nicaragua" to "Managua",
        "New Zealand" to "Wellington",
        "Norway" to "Oslo",
        "UAE" to "Abu Dhabi",
        "Oman" to "Muscat",
        "St. Helena" to "Jamestown",
        "Pakistan" to "Islamabad",
        "Palau" to "Ngerulmud",
        "Panama" to "Panama",
        "Papua New Guinea" to "Port Moresby",
        "Paraguay" to "Asuncion",
        "Peru" to "Lima",
        "Poland" to "Warsaw",
        "Portugal" to "Lisbon",
        "Puerto Rico" to "San Juan",
        "Reunion" to "Saint-Deni",
        "Russia" to "Moscow",
        "Rwanda" to "Kigali",
        "Romania" to "Bucharest",
        "Salvador" to "San Salvador",
        "Samoa" to "Apia",
        "San Marino" to "San Marino",
        "Sao Tome and Principe" to "Sao Tome",
        "Saudi Arabia" to "Riyadh",
        "North Korea" to "Pyongyang",
        "Seychelles" to "Victoria",
        "Senegal" to "Dakar",
        "Saint-Martin" to "Marigot",
        "Saint Vincent and the Grenadines" to "Kingstown",
        "Saint Kitts and Nevis" to "Buster",
        "Saint Lucia" to "Castries",
        "Serbia" to "Belgrade",
        "Singapore" to "Singapore",
        "Syria" to "Damascus",
        "Slovakia" to "Bratislava",
        "Slovenia" to "Ljubljana",
        "Solomon Islands" to "Honiara",
        "Somalia" to "Mogadishu",
        "Sudan" to "Khartoum",
        "Suriname" to "Paramaribo",
        "USA" to "Washington",
        "Sierra Leone" to "Freetown",
        "Tajikistan" to "Dushanbe",
        "Taiwan" to "Taipei",
        "Thailand" to "Bangkok",
        "Tanzania" to "Dodoma, Dar es Salaam",
        "Togo" to "Lome",
        "Tonga" to "Nukualofa",
        "Trinidad and Tobago" to "Port of Spain",
        "Tuvalu" to "Funafuti",
        "Tunisia" to "Tunisia",
        "Turkmenistan" to "Ashgabat",
        "Turkey" to "Ankara",
        "Uganda" to "Kampala",
        "Uzbekistan" to "Tashkent",
        "Ukraine" to "Kiev",
        "Wallis and Futuna" to "Mata-Utu",
        "Uruguay" to "Montevideo",
        "Fiji" to "Suva",
        "Philippines" to "Manila",
        "Finland" to "Helsinki",
        "France" to "Paris",
        "Croatia" to "Zagreb",
        "Central African Republic" to "Bangui",
        "Chad" to "N'Djamena",
        "Montenegro" to "Podgorica",
        "Czech Republic" to "Prague",
        "Chile" to "Santiago",
        "Switzerland" to "Bern",
        "Sweden" to "Stockholm",
        "Sri Lanka" to "Sri Jayewardenepura Kotte",
        "Ecuador" to "Quito",
        "Equatorial Guinea" to "Malabo",
        "Eritrea" to "Asmara",
        "Estonia" to "Tallinn",
        "Ethiopia" to "Cape Town Pretoria",
        "South Korea" to "Kingston",
        "Japan" to "Tokyo"
    )
}
